### ISSUE TITLE
Do you plan to update your plugin for Sketch 40?

### ISSUE THREAD

**Issue by edge0703** [tjerabek/sketch-uifaces#1]
I want to mention it in The Sketch Handbook (http://www.sketch-handbook.com/), but only if it works with the current version of Sketch.

**Comment by tjerabek** [comment]
I updated the plugin yesterday. It works on 40.1. Thank you for mention!

**Comment by edge0703** [comment]
Yep, you are right, I had to reinstall it. Thanks for your quick help!
